GunplaOnlineShop/GunplaOnlineShop/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace GunplaOnlineShop.Models
{
    public class Category
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(30)]
        [StringLength(25)]
        public string Name { get; set; }
        public int? ParentCategoryId { get; set; }  // nullable foreign key --> not all category has parent category
        [ForeignKey("ParentCategoryId")]
        public Category ParentCategory { get; set; }

        public ICollection<ItemCategory> ItemCategories { get; set; }
    }
}

GunplaOnlineShop/GunplaOnlineShop/ViewModels/CollectionViewModel.cs
using GunplaOnlineShop.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime;
using System.Threading.Tasks;

namespace GunplaOnlineShop.ViewModels
{
    public class CollectionViewModel
    {
        public enum SortOrder
        {
            [Display(Name = "Alphabetically, A-Z")]
            NameAscending,
            [Display(Name = "Alphabetically, Z-A")]
            NameDescending,
            [Display(Name = "Price, low to high")]
            PriceAscending,
            [Display(Name = "Price, high to low")]
            PriceDescending,
            [Display(Name = "Best selling")]
            BestSelling,
            Rating,
            [Display(Name = "Release Date, old to new")]
            ReleaseDateAscending,
            [Display(Name = "Release Date, new to old")]
            ReleaseDateDescending
        }
        public string GradeName { get; set; }
        public string SeriesName { get; set; }
        public int PageNumber { get; set; } = 1;
        public int PageSize { get; set; } = 2;

        public Pagination<Item> Items { get; set; }
        public List<Category> SeriesCategories { get; set; }
        public SortOrder SelectedOrder { get; set; } = SortOrder.BestSelling;

        public async Task PaginateItems(IQueryable<Item> items)
        {
            Items = await Pagination<Item>.CreateAsync(items, PageNumber, PageSize);
        }
    }
}

GunplaOnlineShop/GunplaOnlineShop/ViewModels/ProductViewModel.cs
using GunplaOnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GunplaOnlineShop.ViewModels
{
    public class ProductViewModel
    {
        public Item Item { get; set; }
        public AddItemViewModel lineItem { get; set; } = new AddItemViewModel();
    }
}

GunplaOnlineShop/GunplaOnlineShop/Controllers/CollectionController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Security.Principal;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Dasync.Collections;
using GunplaOnlineShop.Data;
using GunplaOnlineShop.Data.Migrations;
using GunplaOnlineShop.Models;
using GunplaOnlineShop.Utilities;
using GunplaOnlineShop.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using static GunplaOnlineShop.QueryObjects.ItemSort;
using static GunplaOnlineShop.ViewModels.CollectionViewModel;

namespace GunplaOnlineShop.Controllers
{
    public class CollectionController : BaseController
    {

        public CollectionController(AppDbContext context, UserManager<ApplicationUser> userManager) : base(context, userManager)
        {
        }

        // GET: /<controller>/
        [Route("/{action}")]
        public async Task<IActionResult> Search([Bind("q,PageNumber,SelectedOrder")] CollectionViewModel model)
        {
            model.PageSize = 50;
            var items = _context.Items
                .AsNoTracking()
                .Include(i => i.ItemCategories)
                 .ThenInclude(i => i.Category)
                .AsQueryable();
            if (!string.IsNullOrEmpty(model.q))
            {
                string[] keywords = model.q.Trim().ToLower().Split(" ");
                foreach (string keyword in keywords)
                {
                    items = items.Where(i => i.Name.ToLower().Contains(keyword)
                                          || i.ItemCategories.Any(ic => ic.Category.Name.ToLower().Contains(keyword))
                                          || i.Description.ToLower().Contains(keyword));
                }
            }

            items = items.OrderItemsBy(model.SelectedOrder);

            await model.PaginateItems(items);
            return View("Category", model);
        }

        [Route("{controller}/{grade}/{series?}")]
        public async Task<IActionResult> Category(string grade, string series, [Bind("PageNumber,SelectedOrder")] CollectionViewModel model)
        {
            var allCategories = await _context.Categories
                .AsNoTracking()
                .ToListAsync();
            var gradeCategory = allCategories.Where(c => c.Name.NameEncode() == grade).FirstOrDefault();
            if (gradeCategory == null) return NotFound();
            model.GradeName = gradeCategory.Name;
            var items = _context.Items
                .AsNoTracking()
                .Include(i => i.ItemCategories)
                .Where(i => i.ItemCategories.Any(ic => ic.CategoryId == gradeCategory.Id));

            if (!string.IsNullOrEmpty(series))
            {
                var seriesCategory = allCategories.Where(c => c.Name.NameEncode() == series).FirstOrDefault();
                int seriesCategoryId = -1;
                if (seriesCategory != null)
                {
                    model.SeriesName = seriesCategory.Name;
                    seriesCategoryId = seriesCategory.Id;
                }
                items = items.Where(b => b.ItemCategories.Any(ic => ic.CategoryId == seriesCategoryId));
            }

            items = items.OrderItemsBy(model.SelectedOrder);

            await model.PaginateItems(items);
            model.SeriesCategories = await _context.Categories
                .AsNoTracking()
                .Where(b => b.ParentCategory.Id == gradeCategory.Id)
                .ToListAsync();

            return View(model);
        }

        [Route("{controller}/{action}/{name}")]
        [Route("{controller}/{grade}/{action}/{name}")]
        public async Task<IActionResult> Products(string grade, string name)
        {
            if (Regex.IsMatch("[^a-zA-Z0-9-]+", name)) return NotFound();
            var item = await _context.Items
                .FromSqlRaw($"SELECT * FROM Items i WHERE REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(LOWER(i.Name), '[^a-zA-Z0-9]+', '-'), '[^a-zA-Z0-9]+$', ''), '^[^a-zA-Z0-9]+', '') = '{name}'")
                .Include(i => i.ItemCategories)
                 .ThenInclude(ic => ic.Category)
                .Include(i => i.Photos)
                .Include(i => i.Reviews)
                .FirstOrDefaultAsync();
            if (item == null) return NotFound();
            var model = new ProductViewModel();
            model.Item = item;
            return View(model);
        }

    }
}

GunplaOnlineShop/GunplaOnlineShop/Views/Collection/ByCategory.cshtml
@model GunplaOnlineShop.ViewModels.CollectionViewModel
@{
    ViewData["title"] = "Shopping By Grade";
}
<style>

    .breadcrumb {
        margin-bottom:0;
    }

    hr {
        margin-top: 0rem;
        margin-bottom: 1rem;
        border: 0;
        border-top: 1px solid rgba(0, 0, 0, 0.1);
    }
    @@media(min-width:576px) {
        .card-deck {
            display: grid;
            grid-template-columns: repeat(1, minmax(150px, 1fr));
            grid-gap: .5rem;
        }
    }
    @@media(min-width:768px) {
        .card-deck {
            display: grid;
            grid-template-columns: repeat(2, minmax(150px, 1fr));
            grid-gap: .5rem;
        }
    }
    @@media(min-width:992px) {
        .card-deck {
            display: grid;
            grid-template-columns: repeat(3, minmax(150px, 1fr));
            grid-gap: .5rem;
        }
    }
    @@media(min-width:1200px) {
        .card-deck {
            display: grid;
            grid-template-columns: repeat(4, minmax(150px, 1fr));
            grid-gap: .5rem;
        }
    }
    .form-inline {
        display: flex;
        align-items: center;
    }
    label {
        margin: 1fr;
    }
</style>

    
<div class="container">
    <div class="row">
        <div class="col-12  d-flex align-items-center">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-light">
                    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page"></li>
                </ol>
            </nav>
        </div>
    </div>
    <hr class="featurette-divider">
    <div class="row">
        <div class="col-2">
            <div class="col-12"><h5>Shop By</h5></div>
            @foreach (var series in Model.Categories)
            {
                <a asp-controller="Collection" asp-action="ByCategory" asp-route-series=@series.Name >
                    <div class="col-12">@series.Name</div>
                </a>
            }
        </div>
        <div class="col-10">
            <div class="row d-flex flex-row-reverse mb-3 ml-3" >
                <form method="get" >
                    <div class="form-inline row">
                        <label>Sort By</label>
                        <select asp-for="SelectedOrder" asp-items="Html.GetEnumSelectList<CollectionViewModel.SortOrder>()" onchange="this.form.submit()" class="form-control"></select>
                    </div>
                </form>
            </div>
            <div class="row">
                <div class="card-deck">
                    @foreach (var item in Model.Items)
                    {
                        <div class="card mt-1 mb-1 ml-1 mr-1 border-0">
                            <a asp-controller="" asp-action="">
                                <img src="~/images/@(item.Name).jpg" class="card-img-top" asp-append-version="true" />
                            </a>
                            <div class="card-body align-items-center justify-content-center">
                                <a asp-controller="" asp-action="">
                                    <div class="row">
                                        <div class="col-12">
                                            <h5 class="card-title stretched-link">@item.Name</h5>
                                        </div>
                                        <div class="col-12">
                                            <p class="card-text font-italic">$@item.Price</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

GunplaOnlineShop/GunplaOnlineShop/Views/Collection/Category.cshtml
@model GunplaOnlineShop.ViewModels.CollectionViewModel
@{
    ViewData["title"] = string.IsNullOrEmpty(Model.SeriesName) ? $"{Model.GradeName} - WhiteBase Gunpla Shop" : $"{Model.GradeName} - Tagged \"{Model.SeriesName}\" - WhiteBase Gunpla Shop";
}
<style>

    .breadcrumb {
        margin-bottom: 0;
    }

    hr {
        margin-top: 0rem;
        margin-bottom: 1rem;
        border: 0;
        border-top: 1px solid rgba(0, 0, 0, 0.1);
    }

    @@media(min-width:576px) {
        .card-deck {
            display: grid;
            grid-template-columns: repeat(1, minmax(150px, 1fr));
            grid-gap: .5rem;
        }
    }

    @@media(min-width:768px) {
        .card-deck {
            display: grid;
            grid-template-columns: repeat(2, minmax(150px, 1fr));
            grid-gap: .5rem;
        }
    }

    @@media(min-width:992px) {
        .card-deck {
            display: grid;
            grid-template-columns: repeat(3, minmax(150px, 1fr));
            grid-gap: .5rem;
        }
    }

    @@media(min-width:1200px) {
        .card-deck {
            display: grid;
            grid-template-columns: repeat(4, minmax(150px, 1fr));
            grid-gap: .5rem;
        }
    }

    .form-inline {
        display: flex;
        align-items: center;
    }

    label {
        margin: 1fr;
    }
</style>


<div class="container">
    <div class="row">
        <div class="col-12  d-flex align-items-center">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-light">
                    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page"></li>
                </ol>
            </nav>
        </div>
    </div>
    <hr class="featurette-divider">
    <div class="row">
        <div class="col-2">
            <div class="col-12"><h5>Shop By</h5></div>
            @foreach (var series in Model.SeriesCategories)
            {
                <a asp-route-series=@GunplaOnlineShop.Utilities.UrlFormat.NameEncode(series.Name)>
                    <div class="col-12">@series.Name</div>
                </a>
            }
        </div>
        <div class="col-10">
            <div class="row d-flex flex-row-reverse mb-3 ml-3">
                <form id="filter" method="get" class="form-group row">
                    <label asp-for="SelectedOrder" class="col-3 col-form-label px-0">Sort By</label>
                    @if (!string.IsNullOrEmpty(Model.q))
                    {
                        @Html.HiddenFor(m => m.q)
                    }
                    @Html.HiddenFor(m => m.PageNumber)
                    <div class="col-9 px-0">
                        <select asp-for="SelectedOrder" asp-items="Html.GetEnumSelectList<GunplaOnlineShop.QueryObjects.ItemSort.SortOrder>()" class="form-control"></select>
                    </div>
                </form>
            </div>
            @await Html.PartialAsync("PaginationPartial", Model.Items)
            <div class="row mt-5">
                <div class="card-deck">
                    @foreach (var item in Model.Items)
                    {
                        var urlEncodedItemName = GunplaOnlineShop.Utilities.UrlFormat.NameEncode(item.Name);
                        <div class="card mt-1 mb-1 ml-1 mr-1 border-0">
                            <a asp-action="Products" asp-route-name="@urlEncodedItemName">
                                <img src="~/images/@(item.Name).jpg" class="card-img-top" asp-append-version="true" />
                            </a>
                            <div class="card-body align-items-center justify-content-center">
                                <a asp-action="Products" asp-route-name="@urlEncodedItemName">
                                    <div class="row">
                                        <div class="col-12">
                                            <h5 class="card-title stretched-link">@item.Name</h5>
                                        </div>
                                        <div class="col-12">
                                            <p class="card-text font-italic">$@item.Price</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    }
                </div>
                @if (!Model.Items.Any())
                {
                    <p class="mx-auto">Sorry, there are no products matching your search.</p>
                }
            </div>
            @await Html.PartialAsync("PaginationPartial", Model.Items)
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(function () {
            $('[name=q]')[0].value = "@Model.q";
        });
        $("#SelectedOrder").change(function () {
            $("[name=PageNumber]")[0].value = 1;
            this.form.submit();
        });
        $(".page-link").click(function () {
            pageNumber = $(this).data("page-number");
            $("[name=PageNumber]")[0].value = pageNumber;
            $("#filter").submit();
        });
    </script>
}

GunplaOnlineShop/GunplaOnlineShop/Views/Collection/Products.cshtml
@model ProductViewModel

@{
    ViewData["title"] = Model.Item.Name + " - WhiteBase Gunpla Shop";
}

<h1>@Model.Item.Name</h1>

@if (Model.Item.Quantity > 0)
{
    <form asp-controller="ShoppingCart" asp-action="AddItemToShoppingCart">
        <div asp-validation-summary="All" class="text-danger ml-2"></div>
        <input hidden id="ItemId" name="ItemId" value="@Model.Item.Id" />
        <input id="Quantity" name="Quantity" type="number" min="1" max="@Model.Item.Quantity" value="1" class="form-control" />
        <button id="addToShoppingCart" type="submit" class="btn btn-outline-primary">ADD TO CART</button>
    </form>
}
else
{
    <button class="btn btn-outline-secondary">SOLD OUT</button>
}